import React from 'react';
import {useNavigation} from "@react-navigation/native";
import {View, Text, ScrollView} from "react-native";

const DatePosts = () => {
  const navigation = useNavigation();
  return (
    <ScrollView
      className="h-full bg-white"
    >
      <Text>
        DatePosts
      </Text>
      <Text>
        DatePosts
      </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text><Text>
      DatePosts
    </Text>
    </ScrollView>
  );
};

export default DatePosts;
